import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.root}>
        <div className={styles.inner}>
          <h1 className={styles.title}>
            Twój <span className={styles.hlght}>Kalendarzyk Winiarza</span> jest
            gotowy Ci pomóc.
          </h1>
          <div className={styles.description}>
            Przekonaj się jak łatwe potrafi być tworzenie i przechowywanie
            notatek o twoich trunkach! Zapisuj swoje ukochane przepisy w
            chmurze, przeglądaj zdjęcia swoich seksownych nastawów, a wszystko
            to ZA DARMO.
          </div>
          <Link href="/calendar/calendar" className={styles.control}>
            Ayyyyyyy, wpuść mnie
          </Link>
        </div>
      </div>
    </>
  );
}
